version: '3.1'

services:
  app:
    image: embraslabs/ruby:3.0.0
    container_name: pessoas-api
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3010 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - redis
    ports:
      - 3010:3010
    volumes:
      - .:/app
      - gems:/.gems
    environment:
      - SECRET_KEY_BASE=development
      - RAILS_ENV=development
      - PORT=3000
      - DATABASE_NAME=pessoas
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env

  postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.0.8-alpine
    command: redis-server
    volumes:
      - redis:/data

volumes:
  gems:
  postgres:
  redis:
